const People =[
    {
        id:1,
        image:"https://www.fillmurray.com/640/360",
        name:"john",
        positon:"director",
        progress:"80%"
    },
    {
        id:2,
        image:"https://www.fillmurray.com/640/350",
        name:"Asiq",
        positon:"director",
        progress:"80%"
    },
    {
        id:3,
        image:"https://www.fillmurray.com/640/390",
        name:"yeasin",
        positon:"director",
        progress:"80%"
    },
    {
        id:4,
        image:"https://www.fillmurray.com/640/360",
        name:"john",
        positon:"director",
        progress:"80%"
    },
    {
        id:5,
        image:"https://www.fillmurray.com/640/350",
        name:"Asiq",
        positon:"director",
        progress:"80%"
    },
    {
        id:6,
        image:"https://www.fillmurray.com/640/390",
        name:"yeasin",
        positon:"director",
        progress:"80%"
    },
    {
        id:4,
        image:"https://www.fillmurray.com/640/360",
        name:"john",
        positon:"director",
        progress:"80%"
    },
    {
        id:5,
        image:"https://www.fillmurray.com/640/350",
        name:"Asiq",
        positon:"director",
        progress:"80%"
    },
    {
        id:6,
        image:"https://www.fillmurray.com/640/390",
        name:"yeasin",
        positon:"director",
        progress:"80%"
    },
]

export default People;